server:
  host: 192.168.100.105
  port: 1883

client:
  client_id: '0'
  host: 192.168.100.105
  data:
    name_data: 'dga' # dga or cifar10
    total_data_in_round: 5000
    num_classes: 10 # dga {2 or 11 or 10} & cifar10 {10}
    labels_drop: [] # input the label dropped

